default_stages: [push]
fail_fast: true
repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: make lint
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
