name: run_tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -U pip wheel
      - run: pip install -e .[test]
      - run: make lint
  tests:
    name: tests
    strategy:
      matrix:
        python: ['3.7', '3.8', '3.9']
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - run: pip install -U pip wheel
      - run: pip install -e .[test]
      - run: make test
